-- mtxrun --script distribution --copy --target=tree --root=c:\data\develop\context\texmf               c:\data\develop\context\manuals/mkiv/public.lua
-- mtxrun --script distribution --copy --target=site --root=c:\data\develop\websites\www.pragma-ade.com c:\data\develop\context\manuals/mkiv/public.lua --dryrun

return {
    category  = "documentation",
    targets   = {
        tree  = {
            sources = "doc/context/sources/documents",
            results = "doc/context/documents",
            objects = { "sources", "results" }
        },
        site = {
            sources = "sources/documents", -- placeholder
            results = "documents",
            objects = { "results" }
        },
    },
    documents = {
        ["shared"] = {
            status  = "okay",
            group   = "general/manuals/mkiv",
            sources = {
                "manuals-explaining-contents.tex",
                "manuals-explaining-cover.tex",
                "manuals-explaining-environment.tex",
                "manuals-xml-environment.tex",
            },
        },
        ["mreadme"] = {
            status  = "okay",
            group   = "general/manuals/mkiv",
            runners = {
                "mtxrun --path=readme --script context mreadme",
                "mtxrun --path=readme --script context missingfiles",
            },
            sources = {
                "mcommon.tex",
                "readme/mreadme.tex",
                "readme/missingfiles.tex",
            },
            results = {
                "readme/mreadme.pdf",
                "readme/missingfiles.pdf",
            },
        },
        ["rules"] = {
            status  = "okay",
            group   = "general/manuals/mkiv",
            runners = {
                "mtxrun --path=rules --script context rules-mkiv",
            },
            sources = {
                "rules/rules-mkiv.tex",
            },
            results = {
                "rules/rules-mkiv.pdf",
            },
        },
        ["charts"] = {
            status  = "okay",
            group   = "general/manuals/mkiv",
            runners = {
                "mtxrun --path=charts --script context charts-mkiv",
            },
            sources = {
                "charts/charts-mkiv.tex",
            },
            results = {
                "charts/charts-mkiv.pdf",
            },
        },
        ["math"] = {
            status  = "okay", -- work in progress
            group   = "general/manuals/mkiv",
            runners = {
                "mtxrun --path=math --script context math-mkiv",
                "mtxrun --path=math --script context math-tweaks",
            },
            sources = {
                "math/math-mkiv.tex",
                "math/math-tweaks.tex",
                "math/math-input.tex",
                "math/math-definitions.tex",
                "math/math-layout.tex",
                "math/math-titlepage.tex",
                "math/math-contents.tex",
                "math/math-introduction.tex",
                "math/math-spacing.tex",
                "math/math-spacing-001.tex",
                "math/math-framing.tex",
                "math/math-framing-001.tex",
                "math/math-numbering.tex",
                "math/math-combining.tex",
                "math/math-features.tex",
                "math/math-suboptimal.tex",
                "math/math-alignments.tex",
                "math/math-tricks.tex",
                "math/math-oddities.tex",
                "math/math-grouping.tex",
                "math/math-fun.tex",
                "math/math-notdone.tex",

                "math/math-fonts.tex",
                "math/math-fonts-helpers.tex",
                "math/math-fonts-accents-001.tex",
                "math/math-fonts-italics-002.tex",
                "math/math-fonts-primes-001.tex",
                "math/math-fonts-scripts-001.tex",
                "math/math-fonts-radicals-001.tex",
            },
            results = {
                "math/math-mkiv.pdf",
                "math/math-tweaks.pdf",
            },
        },
        ["specials"] = {
            status  = "okay",
            group   = "general/specials/mkiv",
            runners = {
             -- "mtxrun --path=specials --script context math-repertoire",
                "mtxrun --path=specials --script context math-repertoire-bonum",
             -- "mtxrun --path=specials --script context math-repertoire-cambria",
                "mtxrun --path=specials --script context math-repertoire-dejavu",
             -- "mtxrun --path=specials --script context math-repertoire-lucida",
                "mtxrun --path=specials --script context math-repertoire-modern",
                "mtxrun --path=specials --script context math-repertoire-pagella",
             -- "mtxrun --path=specials --script context math-repertoire-pennstander",
             -- "mtxrun --path=specials --script context math-repertoire-schola",
                "mtxrun --path=specials --script context math-repertoire-termes",
                --
             -- "mtxrun --path=specials --script context --parallel math-repertoire.lua",
            },
            sources = {
                "specials/math-repertoire.tex",
                "specials/math-repertoire-bonum.tex",
                "specials/math-repertoire-cambria.tex",
                "specials/math-repertoire-dejavu.tex",
                "specials/math-repertoire-lucida.tex",
                "specials/math-repertoire-modern.tex",
                "specials/math-repertoire-pagella.tex",
                "specials/math-repertoire-pennstander.tex",
                "specials/math-repertoire-schola.tex",
                "specials/math-repertoire-termes.tex",
            },
            results = {
             -- "specials/math-repertoire.pdf",
                "specials/math-repertoire-bonum.pdf",
             -- "specials/math-repertoire-cambria.pdf",
                "specials/math-repertoire-dejavu.pdf",
             -- "specials/math-repertoire-lucida.pdf",
                "specials/math-repertoire-modern.pdf",
                "specials/math-repertoire-pagella.pdf",
             -- "specials/math-repertoire-pennstander.pdf",
             -- "specials/math-repertoire-schola.pdf",
                "specials/math-repertoire-termes.pdf",
            },
        },
        ["tools"] = {
            status  = "okay",
            group   = "general/manuals/mkiv",
            runners = {
                "mtxrun --path=tools --script context tools-mkiv",
            },
            sources = {
                "tools/tools-mkiv.tex",
            },
            results = {
                "tools/tools-mkiv.pdf",
            },
        },
        ["columnsets"] = {
            status  = "okay",
            group   = "general/manuals/mkiv",
            runners = {
                "mtxrun --path=columnsets --script context columnsets",
            },
            sources = {
                "columnsets/columnsets.tex",
                "columnsets/columnsets-000.tex",
                "columnsets/columnsets-001.tex",
                "columnsets/columnsets-002.tex",
                "columnsets/columnsets-003.tex",
                "columnsets/columnsets-004.tex",
                "columnsets/columnsets-005.tex",
                "columnsets/columnsets-006.tex",
                "columnsets/columnsets-007.tex",
                "columnsets/columnsets-101.tex",
                "columnsets/columnsets-102.tex",
                "columnsets/columnsets-103.tex",
                "columnsets/columnsets-201.tex",
                "columnsets/columnsets-202.tex",
                "columnsets/columnsets-203.tex",
                "columnsets/columnsets-204.tex",
                "columnsets/columnsets-205.tex",
                "columnsets/columnsets-206.tex",
                "columnsets/columnsets-301.tex",
                "columnsets/columnsets-401.tex",
                "columnsets/columnsets-402.tex",
                "columnsets/columnsets-403.tex",
                "columnsets/columnsets-404.tex",
                "columnsets/columnsets-405.tex",
                "columnsets/columnsets-601.tex",
                "columnsets/columnsets-701.tex",
                "columnsets/columnsets-702.tex",
                "columnsets/columnsets-703.tex",
                "columnsets/columnsets-704.tex",
                "columnsets/columnsets-801.tex",
                "columnsets/columnsets-802.tex",
                "columnsets/columnsets-803.tex",
                "columnsets/columnsets-804.tex",
                "columnsets/columnsets-805.tex",
                "columnsets/columnsets-806.tex",
                "columnsets/columnsets-901.tex",
                "columnsets/columnsets-902.tex",
                "columnsets/columnsets-903.tex",
            },
            results = {
                "columnsets/columnsets.pdf",
            },
        },
        ["pagecolumns"] = {
            status  = "okay",
            group   = "general/manuals/mkiv",
            runners = {
                "mtxrun --path=pagecolumns --script context pagecolumns",
            },
            sources = {
                "pagecolumns/pagecolumns.tex",
                "pagecolumns/pagecolumns-000.tex",
                "pagecolumns/pagecolumns-001.tex",
                "pagecolumns/pagecolumns-002.tex",
                "pagecolumns/pagecolumns-003.tex",
                "pagecolumns/pagecolumns-004.tex",
                "pagecolumns/pagecolumns-005.tex",
                "pagecolumns/pagecolumns-006.tex",
                "pagecolumns/pagecolumns-007.tex", -- not yet there
                "pagecolumns/pagecolumns-008.tex", -- not yet there
                "pagecolumns/pagecolumns-009.tex", -- not yet there
                "pagecolumns/pagecolumns-010.tex", -- not yet there
            },
            results = {
                "pagecolumns/pagecolumns.pdf",
            },
        },
        ["notnow"] = {
            status  = "okay",
            group   = "general/manuals/mkiv",
            runners = {
                "mtxrun --path=notnow --script context notnow",
            },
            sources = {
                "notnow/notnow.tex",
                "notnow/notnow-columns-and-notes.tex",
                "notnow/notnow-sidefloats.tex",
            },
            results = {
                "notnow/notnow.pdf",
            },
        },
        ["xml"] = {
            status  = "okay",
            group   = "general/manuals/mkiv",
            runners = {
                "mtxrun --path=xml --script context xml-mkiv",
            },
            sources = {
                "xml/xml-mkiv.tex",
                --
                "xml/xml-mkiv-commands.tex",
                "xml/xml-mkiv-contents.tex",
                "xml/xml-mkiv-converter.tex",
                "xml/xml-mkiv-examples.tex",
                "xml/xml-mkiv-expressions.tex",
                "xml/xml-mkiv-filtering.tex",
                "xml/xml-mkiv-introduction.tex",
                "xml/xml-mkiv-lookups.tex",
             -- "xml/xml-mkiv-lpath.tex",
                "xml/xml-mkiv-style.tex",
                "xml/xml-mkiv-titlepage.tex",
                "xml/xml-mkiv-tricks.tex",
                --
                "xml/xml-mkiv-01.xml",
                "xml/xml-mkiv-02.xml",
                "xml/xml-mkiv-03.xml",
            },
            results = {
                "xml/xml-mkiv.pdf",
            },
        },
        ["bidi"] = {
            status  = "okay",
            group   = "general/manuals/mkiv",
            runners = {
                "mtxrun --path=bidi --script context bidi",
            },
            sources = {
                "bidi/bidi.tex",
                "bidi/bidi-style.tex",
                "bidi/bidi-titlepage.tex",
                "bidi/bidi-contents.tex",
                "bidi/bidi-introduction.tex",
                "bidi/bidi-fonts.tex",
                "bidi/bidi-mixed.tex",
                "bidi/bidi-numbering.tex",
             -- "bidi/bidi-tables.tex",
                "bidi/bidi-lua.tex",
                "bidi/bidi-vertical.tex",
            },
            results = {
                "bidi/bidi.pdf",
            },
        },
        ["sql"] = {
            status  = "okay",
            group   = "general/manuals/mkiv",
            runners = {
                "mtxrun --path=sql --script context sql-mkiv",
            },
            sources = {
                "sql/sql-mkiv.tex",
                "sql/demo-sql.tex",
            },
            results = {
                "sql/sql-mkiv.pdf",
            },
        },
        ["templates"] = {
            status  = "okay",
            group   = "general/manuals/mkiv",
            runners = {
                "mtxrun --path=templates --script context templates-mkiv",
            },
            sources = {
                "templates/templates-mkiv.tex",
            },
            results = {
                "templates/templates-mkiv.pdf",
            },
        },
        ["lua"] = {
            status  = "okay",
            group   = "general/manuals/mkiv",
            runners = {
                "mtxrun --path=lua --script context lua-mkiv",
            },
            sources = {
                "lua/lua-mkiv.tex",
            },
            results = {
                "lua/lua-mkiv.pdf",
            },
        },
        ["epub"] = {
            status  = "okay",
            group   = "general/manuals/mkiv",
            runners = {
                "mtxrun --path=epub --script context epub-mkiv",
                "mtxrun --path=epub --script context epub-mkiv-demo",
                "mtxrun --path=epub --script epub    epub-mkiv-demo --make --purge --rename --svgmath",
            },
            sources = {
                "epub/epub-mkiv.tex",
                "epub/epub-mkiv-demo.tex",
            },
            results = {
                "epub/epub-mkiv.pdf",
                "epub/epub-mkiv-demo.pdf",
                "epub/epub-mkiv-demo.epub",
            },
        },
        ["musing"] = {
            status  = "okay",
            group   = "general/manuals/mkiv",
            runners = {
                "mtxrun --path=luatex --script context musings",
            },
            sources = {
                "musings/musings.tex",
                "musings/musings-style.tex",
                "musings/musings-titlepage.tex",
                "musings/musings-introduction.tex",
                "musings/musings-contents.tex",
                --
                "musings/musings-children.tex",
                "musings/musings-perception.tex",
                "musings/musings-whytex.tex",
                "musings/musings-staygo.tex",
                "musings/musings-stability.tex",
                "musings/musings-roadmap.tex",
                "musings/musings-names.tex",
                "musings/musings-plain.tex",
                "musings/musings-toocomplex.tex",
                "musings/musings-manuals.tex",
                "musings/musings-performance.tex",
                "musings/musings-history.tex",
                "musings/musings-treasures.tex",
             -- "musings/musings-whytex-again.tex",

                "musings/musings-dontusetex.tex",
                "musings/eutypon-gr-e-blog-21-02-13-why-i-do-not-like-luatex.png",

                "musings/musings-speed.tex",
                "musings/musings-unicode.tex",
                "musings/musings-texlive.tex",
                "musings/musings-hownotto.tex",
             -- "musings/musings-security.tex",
             -- "musings/musings-usage.tex",
                "musings/musings-sideeffects.tex",
                "musings/musings-perfection.tex", -- included as teaser
                "musings/musings-assumptions.tex",
             -- "musings/musings-green.tex",
             -- "musings/musings-cheats.tex",

                "musings/musings-units.tex",
                "musings/musings-units-design.pdf",
                "musings/musings-units-final-1.png",
                "musings/musings-units-final-2.png",
                "musings/musings-units-final-3.png",
                "musings/musings-units-dek-thumb-1.png",
                "musings/musings-units-dek-thumb-2.png",
                "musings/musings-units-dek-thumb-closeup.jpg",
                "musings/musings-units-dek-fasc0b-13.pdf",

                "musings/musings-kerns.tex",
                "musings/musings-kerns-Q-pdftex",
                "musings/musings-kerns-Q-luatex",
                "musings/musings-kerns-A-luametatex.pdf",

                "musings/musings-deserved.tex",
                "musings/musings-riscv.tex",
                "musings/musings-features.tex", -- tugboat 2024

                "musings/musings-viewers.tex",
             -- "musings/musings-highlight-acrobat.png",
             -- "musings/musings-highlight-fixed-okular.png",
             -- "musings/musings-highlight-okular.png",
             -- "musings/musings-highlight-rotated-acrobat.png",
             -- "musings/musings-highlight-rotated-okular.png",
             -- "musings/musings-highlight-rotated-sumatra.png",
             -- "musings/musings-highlight-sumatra.png",
             -- "musings/musings-selection-rotated-acrobat.png",
             -- "musings/musings-selection-rotated-okular.png",
             -- "musings/musings-selection-rotated-sumatra.png",
             -- "musings/musings-units-dek-thumb-1.png",
             -- "musings/musings-units-dek-thumb-2.png",
             -- "musings/musings-units-final-1.png",
             -- "musings/musings-units-final-2.png",
             -- "musings/musings-units-final-3.png",
             -- "musings/musings-units-prototype.png",

                "musings/musings-shift.tex",
             -- "musings/musings-neat.tex",       -- tugboat
                "musings/musings-illiterate.tex", -- maps
                "musings/musings-fake.tex",
                "musings/musings-rpi.tex",
             -- "musings/musings-nottagging.tex",
             -- "musings/musings-archiving.tex",

                ----------------------------

                "musings/musings-basic.tex", -- stand alone
            },
            results = {
                "musings/musings.pdf",
                --

          --    "musings/musings-children.pdf",
          --    "musings/musings-perception.pdf",
          --    "musings/musings-whytex.pdf",
          --    "musings/musings-staygo.pdf",
          --    "musings/musings-stability.pdf",
          --    "musings/musings-roadmap.pdf",
          --    "musings/musings-names.pdf",
          --    "musings/musings-plain.pdf",
          --    "musings/musings-toocomplex.pdf",
          --    "musings/musings-manuals.pdf",
          --    "musings/musings-performance.pdf",
          --    "musings/musings-history.pdf",
          --    "musings/musings-treasures.pdf",
          -- -- "musings/musings-whytex-again.pdf",
          --
          --    "musings/musings-dontusetex.pdf",
          --
          --    "musings/musings-speed.pdf",
          --    "musings/musings-unicode.pdf",
          --    "musings/musings-texlive.pdf",
          --    "musings/musings-hownotto.pdf",
          -- -- "musings/musings-security.pdf",
          -- -- "musings/musings-usage.pdf",
          --    "musings/musings-sideeffects.pdf",
          --    "musings/musings-perfection.pdf", -- included as teaser
          --    "musings/musings-assumptions.pdf",
          -- -- "musings/musings-green.pdf",
          -- -- "musings/musings-cheats.pdf",
          --
          -- -- "musings/musings-units.pdf",
          -- -- "musings/musings-kerns.pdf",
          --
          --    "musings/musings-deserved.pdf",
          --    "musings/musings-riscv.pdf",
          --
          -- -- "musings/musings-features.pdf", -- tugboat 2024
          --
          --    "musings/musings-viewers.pdf",
          --
          --    "musings/musings-shift.pdf",
          -- -- "musings/musings-neat.pdf",       -- to be checked
          -- -- "musings/musings-illiterate.pdf", -- maps
          -- -- "musings/musings-fake.pdf",       -- to be checked

                ----------------------------

                "musings/musings-basic.pdf", -- stand alone
            },
        },
        ["texit"] = {
            status  = "okay",
            group   = "general/manuals/mkiv",
            runners = {
                "mtxrun --path=luatex --script context texit",
            },
            sources = {
                "texit/texit.tex",
                "texit/texit-style.tex",
                "texit/texit-titlepage.tex",
                "texit/texit-introduction.tex",
                "texit/texit-contents.tex",
                "texit/texit-lookahead.tex",
                "texit/texit-conditions.tex",
                "texit/texit-leaders.tex",
            },
            results = {
                "texit/texit.pdf",
            },
        },
        ["luatex"] = {
            status  = "okay",
            group   = "general/manuals/mkiv",
            runners = {
                "mtxrun --path=luatex --script context luatex",
            },
            sources = {
                "luatex/luatex.tex",
                "luatex/luatex-contents.tex",
                "luatex/luatex-firstpage.tex",
                "luatex/luatex-preamble.tex",
                "luatex/luatex-enhancements.tex",
                "luatex/luatex-fonts.tex",
                "luatex/luatex-introduction.tex",
                "luatex/luatex-languages.tex",
                "luatex/luatex-libraries.tex",
                "luatex/luatex-logos.tex",
                "luatex/luatex-lua.tex",
                "luatex/luatex-math.tex",
                "luatex/luatex-modifications.tex",
                "luatex/luatex-nodes.tex",
                "luatex/luatex-style.tex",
                "luatex/luatex-titlepage.tex",
                "luatex/luatex-statistics.tex",
                "luatex/luatex-registers.tex",
                "luatex/luatex-remarks.tex",
            },
            results = {
                "luatex/luatex.pdf",
            },
        },
        ["units"] = {
            status  = "okay",
            group   = "general/manuals/mkiv",
            runners = {
                "mtxrun --path=units --script context units-mkiv",
            },
            sources = {
                "units/units-mkiv.tex",
            },
            results = {
                "units/units-mkiv.pdf",
            },
        },
        ["workflows"] = {
            status  = "okay",
            group   = "general/manuals/mkiv",
            runners = {
                "mtxrun --path=workflows --script context workflows-mkiv",
            },
            sources = {
                "workflows/workflows-mkiv.tex",
                "workflows/workflows-style.tex",
                "workflows/workflows-titlepage.tex",
                "workflows/workflows-contents.tex",
                "workflows/workflows-introduction.tex",
                "workflows/workflows-running.tex",
                "workflows/workflows-resources.tex",
                "workflows/workflows-graphics.tex",
                "workflows/workflows-suspects.tex",
                "workflows/workflows-injectors.tex",
                "workflows/workflows-setups.tex",
                "workflows/workflows-xml.tex",
                "workflows/workflows-synctex.tex",
                "workflows/workflows-parallel.tex",
                "workflows/workflows-hashed.tex",
                "workflows/workflows-userdata.tex",
            },
            results = {
                "workflows/workflows-mkiv.pdf",
            },
        },
        ["spacing"] = {
            status  = "okay",
            group   = "general/manuals/mkiv",
            runners = {
                "mtxrun --path=spacing --script context spacing-mkiv",
            },
            sources = {
                "spacing/spacing-mkiv.tex",
                "spacing/spacing-style.tex",
                "spacing/spacing-titlepage.tex",
                "spacing/spacing-contents.tex",
                "spacing/spacing-introduction.tex",
                "spacing/spacing-linecorrection.tex",
                "spacing/spacing-periods.tex",
                "spacing/spacing-spaces.tex",
            },
            results = {
                "spacing/spacing-mkiv.pdf",
            },
        },
        ["spreadsheet"] = {
            status  = "okay",
            group   = "general/manuals/mkiv",
            runners = {
                "mtxrun --path=spreadsheets --script context spreadsheets-mkiv",
            },
            sources = {
                "spreadsheets/spreadsheets-mkiv.tex",
            },
            results = {
                "spreadsheets/spreadsheets-mkiv.pdf",
            },
        },
        ["swiglib"] = {
            status  = "okay",
            group   = "general/manuals/mkiv",
            runners = {
                "mtxrun --path=swiglib --script context swiglib-mkiv",
            },
            sources = {
                "swiglib/swiglib-mkiv.tex",
                "swiglib/swiglib-mkiv-gm-1.png",
                "swiglib/swiglib-mkiv-gm-1.pdf",
                "swiglib/swiglib-mkiv-gm-1.jpg",
            },
            results = {
                "swiglib/swiglib-mkiv.pdf",
            },
        },
        ["libraries"] = {
            status  = "okay",
            group   = "general/manuals/mkiv",
            runners = {
                "mtxrun --path=libraries --script context libraries-mkiv",
            },
            sources = {
                "libraries/libraries-mkiv.tex",
            },
            results = {
                "libraries/libraries-mkiv.pdf",
            },
        },
        ["interaction"] = {
            status  = "okay",
            group   = "general/manuals/mkiv",
            runners = {
                "mtxrun --path=interaction --script context interaction",
            },
            sources = {
                "interaction/interaction.tex",
                --
                "interaction/interaction-style.tex",
                --
                "interaction/interaction-titlepage.tex",
                "interaction/interaction-contents.tex",
                "interaction/interaction-introduction.tex",
                --
                "interaction/interaction-annotations.tex",
                "interaction/interaction-enabling.tex",
                "interaction/interaction-actions.tex",
                "interaction/interaction-hyperlinks.tex",
                "interaction/interaction-structure.tex",
                "interaction/interaction-comments.tex",
                "interaction/interaction-attachments.tex",
                "interaction/interaction-bookmarks.tex",
                "interaction/interaction-javascript.tex",
                "interaction/interaction-buttons.tex",
                "interaction/interaction-menus.tex",
                "interaction/interaction-progress.tex",
                "interaction/interaction-widgets.tex",
                "interaction/interaction-transitions.tex",
                "interaction/interaction-importing.tex",
                "interaction/interaction-tagging.tex",
            },
            results = {
                "interaction/interaction.pdf",
            },
        },
        ["steps"] = {
            status  = "okay",
            group   = "general/manuals/mkiv",
            runners = {
                "mtxrun --path=steps --script context steps-mkiv",
            },
            sources = {
                "steps/steps-mkiv.tex",
                "manuals-xml-environment.tex",
            },
            results = {
                "steps/steps-mkiv.pdf",
            },
        },
        ["mathml"] = {
            status  = "okay",
            group   = "general/manuals/mkiv",
            runners = {
                "mtxrun --path=mathml --script context mmlprime",
            },
            sources = {
                "mathml/mmlprime.tex",
                "mathml/mmlexamp.tex",
                "mathml/envexamp.tex",
                --
                "mathml/pc-d-001.xml",
                "mathml/pc-d-002.xml",
                "mathml/pc-d-003.xml",
                "mathml/pc-d-004.xml",
                "mathml/pc-d-005.xml",
                "mathml/pc-d-006.xml",
                "mathml/pc-d-007.xml",
                "mathml/pc-d-008.xml",
                "mathml/pc-d-009.xml",
                "mathml/pc-d-010.xml",
                "mathml/pc-d-011.xml",
                "mathml/pc-d-043.xml",
                "mathml/pc-d-051.xml",
                --
                "mathml/pc-i-022.xml",
                "mathml/pc-i-380.xml",
                --
                "mathml/pc-s-001.xml",
                "mathml/pc-s-002.xml",
                "mathml/pc-s-003.xml",
                "mathml/wh-s-001.xml",
                "mathml/wh-s-002.xml",
                --
                "mathml/wh-l-001.xml",
                "mathml/wh-l-002.xml",
                "mathml/wh-l-003.xml",
                "mathml/wh-l-004.xml",
                --
                "mathml/wh-g-001.xml",
                "mathml/wh-g-002.xml",
                "mathml/wh-g-003.xml",
                "mathml/wh-g-004.xml",
                "mathml/wh-g-005.xml",
                "mathml/wh-g-006.xml",
                "mathml/wh-g-007.xml",
                "mathml/wh-g-008.xml",
                "mathml/wh-g-009.xml",
                "mathml/wh-g-010.xml",
                "mathml/wh-g-011.xml",
                "mathml/wh-g-012.xml",
                "mathml/wh-g-013.xml",
                "mathml/wh-g-014.xml",
                "mathml/wh-g-015.xml",
                "mathml/wh-g-016.xml",
            },
            results = {
                "mathml/mmlprime.pdf",
                "mathml/mmlexamp.pdf",
            },
        },
        ["tiptrick"] = {
            status  = "okay",
            group   = "general/manuals/mkiv",
            runners = {
                "mtxrun --path=tiptrick --script context tiptrick",
            },
            sources = {
                "tiptrick/tiptrick.tex",
                "tiptrick/tiptrick.xml",
            },
            results = {
                "tiptrick/tiptrick.pdf",
            },
        },
        ["fonts"] = {
            status  = "okay",
            group   = "general/manuals/mkiv",
            runners = {
                "mtxrun --path=fonts --script context mkiv-fonts",
            },
            sources = {
                "fonts/fonts-mkiv.tex",

                "manuals-explaining-environment.tex",
                "manuals-explaining-cover.tex",
                "manuals-explaining-contents.tex",

                "fonts/fonts-environment.tex",

                "fonts/fonts-introduction.tex",
                "fonts/fonts-formats.tex",
                "fonts/fonts-modes.tex",
                "fonts/fonts-lookups.tex",
                "fonts/fonts-methods.tex",
                "fonts/fonts-features.tex",
                "fonts/fonts-scripts.tex",
                "fonts/fonts-math.tex",
                "fonts/fonts-extensions.tex",
                "fonts/fonts-hooks.tex",
                "fonts/fonts-tricks.tex",
                "fonts/fonts-compact.tex",

                "fonts/fonts-appendix.tex",

                "fonts/fonts-demo-rule.lua",

            },
            results = {
                "fonts/fonts-mkiv.pdf",
            },
        },
        ["languages"] = {
            status  = "okay",
            group   = "general/manuals/mkiv",
            runners = {
                "mtxrun --path=languages --script context languages-mkiv",
            },
            sources = {
                "languages/languages-mkiv.tex",

                "manuals-explaining-environment.tex",
                "manuals-explaining-cover.tex",
                "manuals-explaining-contents.tex",

                "languages/languages-environment.tex",

                "languages/languages-introduction.tex",
                "languages/languages-basics.tex",
                "languages/languages-hyphenation.tex",
                "languages/languages-labels.tex",
                "languages/languages-numbering.tex",
                "languages/languages-typesettingv",
                "languages/languages-goodies.tex",
                "languages/languages-sorting.tex",
                "languages/languages-options.tex",
                "languages/languages-appendix.tex",
            },
            results = {
                "languages/languages-mkiv.pdf",
            },
        },
        ["colors"] = {
            status  = "okay",
            group   = "general/manuals/mkiv",
            runners = {
                "mtxrun --path=colors --script context colors-mkiv",
            },
            sources = {
                "colors/colors-mkiv.tex",

                "manuals-explaining-environment.tex",
                "manuals-explaining-cover.tex",
                "manuals-explaining-contents.tex",

                "colors/colors-environment.tex",

                "colors/colors-introduction.tex",
                "colors/colors-basics.tex",
                "colors/colors-metafun.tex",
                "colors/colors-graphics.tex",

                "2019-sneaky-bw-lowres.png",
                "mill.png",
                "hacker.jpg",
            },
            results = {
                "colors/colors-mkiv.pdf",
            },
        },
        ["cld"] = {
            status  = "okay",
            group   = "general/manuals/mkiv",
            runners = {
                "mtxrun --path=cld --script context cld-mkiv",
            },
            sources = {
                "cld/cld-mkiv.tex",

                "cld/cld-environment.tex",

                "cld/cld-titlepage.tex",

                "cld/cld-contents.tex",
                "cld/cld-introduction.tex",

                "cld/cld-abitoflua.tex",
                "cld/cld-gettingstarted.tex",
                "cld/cld-moreonfunctions.tex",
                "cld/cld-afewdetails.tex",
                "cld/cld-somemoreexamples.tex",
                "cld/cld-graphics.tex",
                "cld/cld-macros.tex",
                "cld/cld-verbatim.tex",
                "cld/cld-logging.tex",
                "cld/cld-luafunctions.tex",
                "cld/cld-ctxfunctions.tex",
                "cld/cld-scanners.tex",
                "cld/cld-variables.tex",
                "cld/cld-callbacks.tex",
                "cld/cld-backendcode.tex",
                "cld/cld-goodies.tex",
                "cld/cld-nicetoknow.tex",
             -- "cld/cld-xml.tex",
                "cld/cld-summary.tex",
                "cld/cld-specialcommands.tex",
                "cld/cld-files.tex",

             -- "cld/cld-index.tex",
            },
            results = {
                "cld/cld-mkiv.pdf",
            },
        },
        ["publications"] = {
            status  = "okay",
            group   = "general/manuals/mkiv",
            runners = {
                "mtxrun --path=publications --script context mkiv-publications",
            },
            sources = {
                "publications/mkiv-publications.tex",
                "publications/mkiv-publications.lua",
                "publications/mkiv-publications.bib",

                "publications/publications-citations.tex",
                "publications/publications-completeness.tex",
                "publications/publications-contents.tex",
                "publications/publications-customize.tex",
                "publications/publications-database.tex",
                "publications/publications-datasets.tex",
                "publications/publications-exporting.tex",
                "publications/publications-extensions.tex",
                "publications/publications-fields.tex",
                "publications/publications-introduction.tex",
                "publications/publications-journals.tex",
                "publications/publications-lua.tex",
                "publications/publications-otheruse.tex",
                "publications/publications-overviews.tex",
                "publications/publications-performance.tex",
                "publications/publications-quick.tex",
                "publications/publications-quick-example.tex",
                "publications/publications-rendering.tex",
                "publications/publications-style.tex",
                "publications/publications-titlepage.tex",
                "publications/publications-tracing.tex",

                "publications/publications-en.xml",

                "publications/boekplan.bib",
                "publications/duane.bib",
                "publications/manuals.bib",
                "publications/template-clean.bib",
             -- "publications/tugboat.bib",

             -- "publications/journals.lua",
             -- "publications/journals.txt",

                "publications/C6H6O.bib",
                "publications/122176.mol",
                "publications/122176.pdf",
                "publications/124484.mol",
                "publications/124484.pdf",
                "publications/4953942.mol",
                "publications/4953942.pdf",
                "publications/971.mol",
                "publications/971.pdf",
            },
            results = {
                "publications/mkiv-publications.pdf",
            },
        },
        ["xtables"] = {
            status  = "okay",
            group   = "general/manuals/mkiv",
            runners = {
                "mtxrun --path=xtables --script context xtables-mkiv",
            },
            sources = {
                "xtables/xtables-mkiv.tex",
            },
            results = {
                "xtables/xtables-mkiv.pdf",
            },
        },
        ["graphics"] = {
            status  = "okay",
            group   = "general/manuals/mkiv",
            runners = {
                "mtxrun --path=graphics --script context graphics",
            },
            sources = {
                "graphics/graphics.tex",
            },
            results = {
                "graphics/graphics.pdf",
            },
        },
        ["pdfmerge"] = {
            status  = "okay",
            group   = "general/manuals/mkiv",
            runners = {
             -- "mtxrun --path=pdfmerge --script unzip pdfmerge-testfiles.zip",
                "mtxrun --path=pdfmerge --script context pdfmerge",
            },
            sources = {
                "pdfmerge/pdfmerge.tex",
                "pdfmerge/pdfmerge-testfiles.zip",
            },
            results = {
                "pdfmerge/pdfmerge.pdf",
            },
        },
        ["nodes"] = {
            status  = "okay",
            group   = "general/manuals/mkiv",
            runners = {
                "mtxrun --path=nodes --script context nodes",
            },
            sources = {
                "nodes/nodes.tex",
                "nodes/nodes-sun-pia-03149.jpg",
                "nodes/nodes-sun-pia-03150.jpg",
            },
            results = {
                "nodes/nodes.pdf",
            },
        },
        ["start"] = {
            status  = "okay",
            group   = "general/manuals/mkiv",
            runners = {
                "mtxrun --path=start/en --script context ma-cb-en",
             -- "mtxrun --path=start/nl --script context ma-cb-nl",
            },
            sources = {

                -- styles --

                "start/ma-cb.tex",
                "start/ma-cb-abbreviations.tex",
                "start/ma-cb-colofon.tex",
                "start/ma-cb-copyright.tex",
                "start/ma-cb-graphics.tex",
                "start/ma-cb-links.tex",
                "start/ma-cb-screen.tex",
                "start/ma-cb-style.tex",

                -- graphics --

                "start/graphics/ma-cb-00.eps",
                "start/graphics/fig-page-areas-en.eps",
             -- "start/graphics/fig-page-areas-nl.eps",
                "start/graphics/fig-page-parameters-en.eps",
             -- "start/graphics/fig-page-parameters-nl.eps",
                "start/graphics/ma-cb-00.mp",
                "start/graphics/cow.pdf",
                "start/graphics/fig-page-areas-en.pdf",
             -- "start/graphics/fig-page-areas-nl.pdf",
                "start/graphics/fig-page-parameters-en.pdf",
             -- "start/graphics/fig-page-parameters-nl.pdf",
                "start/graphics/ma-cb-00.pdf",
                "start/graphics/minibook-en.pdf",
             -- "start/graphics/minibook-nl.pdf",
                "start/graphics/ma-cb-01.png",
                "start/graphics/ma-cb-03.png",
                "start/graphics/ma-cb-04.png",
                "start/graphics/ma-cb-07.png",
                "start/graphics/ma-cb-08.png",
                "start/graphics/ma-cb-12.png",
                "start/graphics/ma-cb-13.png",
                "start/graphics/ma-cb-15.png",
                "start/graphics/ma-cb-16.png",
                "start/graphics/ma-cb-18.png",
                "start/graphics/ma-cb-19.png",
                "start/graphics/ma-cb-20.png",
                "start/graphics/ma-cb-21.png",
                "start/graphics/ma-cb-22.png",
                "start/graphics/ma-cb-23.png",
                "start/graphics/ma-cb-24.png",
                "start/graphics/ma-cb-25.png",
                "start/graphics/ma-cb-25-edited.png",
                "start/graphics/ma-cb-26.png",
                "start/graphics/minibook-en.tex",
             -- "graphics/minibook-nl.tex",

                -- english version --

                "start/en/hasseltbook.bib",
                "start/en/hasseltbook.pdf",
                "start/en/hasseltbook.tex",
                "start/en/ma-cb-en.tex",
                "start/en/ma-cb-en-alignments.tex",
                "start/en/ma-cb-en-backpage.tex",
                "start/en/ma-cb-en-bibliography.tex",
                "start/en/ma-cb-en-chemical.tex",
                "start/en/ma-cb-en-citations.tex",
                "start/en/ma-cb-en-color.tex",
                "start/en/ma-cb-en-columns.tex",
                "start/en/ma-cb-en-commandlist.tex",
                "start/en/ma-cb-en-commands.tex",
                "start/en/ma-cb-en-composedcharacters.tex",
                "start/en/ma-cb-en-descriptions.tex",
                "start/en/ma-cb-en-document.tex",
                "start/en/ma-cb-en-enumerations.tex",
                "start/en/ma-cb-en-errors.tex",
                "start/en/ma-cb-en-figures.tex",
                "start/en/ma-cb-en-floats.tex",
                "start/en/ma-cb-en-fonts.tex",
                "start/en/ma-cb-en-footnotes.tex",
                "start/en/ma-cb-en-framedtexts.tex",
                "start/en/ma-cb-en-frames.tex",
                "start/en/ma-cb-en-gettingstarted.tex",
                "start/en/ma-cb-en-headers.tex",
                "start/en/ma-cb-en-heads.tex",
                "start/en/ma-cb-en-interactivity.tex",
                "start/en/ma-cb-en-introduction.tex",
                "start/en/ma-cb-en-itemizations.tex",
                "start/en/ma-cb-en-language.tex",
                "start/en/ma-cb-en-layers.tex",
                "start/en/ma-cb-en-layout.tex",
                "start/en/ma-cb-en-margintexts.tex",
                "start/en/ma-cb-en-math.tex",
                "start/en/ma-cb-en-mathcharacters.tex",
                "start/en/ma-cb-en-metapost.tex",
                "start/en/ma-cb-en-modules.tex",
                "start/en/ma-cb-en-pagebackgrounds.tex",
                "start/en/ma-cb-en-pages.tex",
                "start/en/ma-cb-en-paragraphs.tex",
                "start/en/ma-cb-en-presentations.tex",
                "start/en/ma-cb-en-processingfiles.tex",
                "start/en/ma-cb-en-references.tex",
                "start/en/ma-cb-en-registers.tex",
                "start/en/ma-cb-en-runtimefiles.tex",
                "start/en/ma-cb-en-setupcommands.tex",
                "start/en/ma-cb-en-sortedlists.tex",
                "start/en/ma-cb-en-specialcharacters.tex",
                "start/en/ma-cb-en-structure.tex",
                "start/en/ma-cb-en-support.tex",
                "start/en/ma-cb-en-synonyms.tex",
                "start/en/ma-cb-en-tables.tex",
                "start/en/ma-cb-en-tablesofcontent.tex",
                "start/en/ma-cb-en-tabulations.tex",
                "start/en/ma-cb-en-textbackgrounds.tex",
                "start/en/ma-cb-en-texteditor.tex",
                "start/en/ma-cb-en-textree.tex",
                "start/en/ma-cb-en-units.tex",
                "start/en/ma-cb-en-usersetups.tex",
                "start/en/ma-cb-en-whatever.tex",
                "start/en/ma-cb-language.tex",
                "start/en/sounds-001.tex",

                -- dutch version --

             -- "start/nl/hasseltbook.pdf",
             -- "start/nl/ma-cb-nl.pdf",
             -- "start/nl/hasseltbook.tex",
             -- "start/nl/ma-cb-language.tex",
             -- "start/nl/ma-cb-nl.tex",
             -- "start/nl/ma-cb-nl-alignments.tex",
             -- "start/nl/ma-cb-nl-backpage.tex",
             -- "start/nl/ma-cb-nl-bibliography.tex",
             -- "start/nl/ma-cb-nl-chemical.tex",
             -- "start/nl/ma-cb-nl-citations.tex",
             -- "start/nl/ma-cb-nl-color.tex",
             -- "start/nl/ma-cb-nl-columns.tex",
             -- "start/nl/ma-cb-nl-commandlist.tex",
             -- "start/nl/ma-cb-nl-commands.tex",
             -- "start/nl/ma-cb-nl-composedcharacters.tex",
             -- "start/nl/ma-cb-nl-descriptions.tex",
             -- "start/nl/ma-cb-nl-document.tex",
             -- "start/nl/ma-cb-nl-enumerations.tex",
             -- "start/nl/ma-cb-nl-errors.tex",
             -- "start/nl/ma-cb-nl-figures.tex",
             -- "start/nl/ma-cb-nl-floats.tex",
             -- "start/nl/ma-cb-nl-fonts.tex",
             -- "start/nl/ma-cb-nl-footnotes.tex",
             -- "start/nl/ma-cb-nl-framedtexts.tex",
             -- "start/nl/ma-cb-nl-frames.tex",
             -- "start/nl/ma-cb-nl-gettingstarted.tex",
             -- "start/nl/ma-cb-nl-headers.tex",
             -- "start/nl/ma-cb-nl-heads.tex",
             -- "start/nl/ma-cb-nl-interactivity.tex",
             -- "start/nl/ma-cb-nl-introduction.tex",
             -- "start/nl/ma-cb-nl-itemizations.tex",
             -- "start/nl/ma-cb-nl-language.tex",
             -- "start/nl/ma-cb-nl-layers.tex",
             -- "start/nl/ma-cb-nl-layout.tex",
             -- "start/nl/ma-cb-nl-margintexts.tex",
             -- "start/nl/ma-cb-nl-math.tex",
             -- "start/nl/ma-cb-nl-mathcharacters.tex",
             -- "start/nl/ma-cb-nl-metapost.tex",
             -- "start/nl/ma-cb-nl-modules.tex",
             -- "start/nl/ma-cb-nl-pagebackgrounds.tex",
             -- "start/nl/ma-cb-nl-pages.tex",
             -- "start/nl/ma-cb-nl-paragraphs.tex",
             -- "start/nl/ma-cb-nl-presentations.tex",
             -- "start/nl/ma-cb-nl-processingfiles.tex",
             -- "start/nl/ma-cb-nl-references.tex",
             -- "start/nl/ma-cb-nl-registers.tex",
             -- "start/nl/ma-cb-nl-runtimefiles.tex",
             -- "start/nl/ma-cb-nl-setupcommands.tex",
             -- "start/nl/ma-cb-nl-sortedlists.tex",
             -- "start/nl/ma-cb-nl-specialcharacters.tex",
             -- "start/nl/ma-cb-nl-structure.tex",
             -- "start/nl/ma-cb-nl-support.tex",
             -- "start/nl/ma-cb-nl-synonyms.tex",
             -- "start/nl/ma-cb-nl-tables.tex",
             -- "start/nl/ma-cb-nl-tablesofcontent.tex",
             -- "start/nl/ma-cb-nl-tabulations.tex",
             -- "start/nl/ma-cb-nl-textbackgrounds.tex",
             -- "start/nl/ma-cb-nl-texteditor.tex",
             -- "start/nl/ma-cb-nl-textree.tex",
             -- "start/nl/ma-cb-nl-units.tex",
             -- "start/nl/ma-cb-nl-usersetups.tex",
             -- "start/nl/ma-cb-nl-whatever.tex",

            },
            results = {
             -- "start/nl/ma-cb-nl.pdf",
                "start/en/ma-cb-en.pdf",
            },
        },
        ["mk"] = {
            status  = "okay",
            group   = "general/manuals/mkiv",
            runners = {
                "mtxrun --path=mk --script context mk",
            },
            sources = {
                "mk/mk.tex",
                "mk/mk-environment.tex",
                "mk/mk-titlepage.tex",
                "mk/mk-contents.tex",
                "mk/mk-introduction.tex",
                "mk/mk-iitoiv.tex",
                "mk/mk-luafitsin.tex",
                "mk/mk-initialization.tex",
                "mk/mk-calcmath.tex",
                "mk/mk-goingutf.tex",
                "mk/mk-fonts.tex",
                "mk/mk-tokenspeak.tex",
                "mk/mk-performance.tex",
                "mk/mk-nodes.tex",
                "mk/mk-dirtytricks.tex",
                "mk/mk-goingbeta.tex",
                "mk/mk-zapfino.tex",
                "mk/mk-arabic.tex",
                "mk/mk-colors.tex",
                "mk/mk-cjk.tex",
                "mk/mk-optimization.tex",
                "mk/mk-xml.tex",
                "mk/mk-breakingapart.tex",
                "mk/mk-memory.tex",
                "mk/mk-nicetoknow.tex",
                "mk/mk-reflection.tex",
                "mk/mk-mplib.tex",
                "mk/mk-mix.tex",
                "mk/mk-punk.tex",
                "mk/mk-open.tex",
                "mk/mk-itworks.tex",
                "mk/mk-fallback.tex",
             -- "mk/mk-dynamics.tex", -- unfinished
             -- "mk/mk-bidi.tex", -- unfinished
             -- "mk/mk-easier.tex", -- unfinished
                "mk/mk-structure.tex",
                "mk/mk-tracking.tex",
                "mk/mk-order.tex",
                "mk/mk-math.tex",
                "mk/mk-code.tex",
                "mk/mk-plain.tex",
                "mk/mk-halfway.tex",
                "mk/mk-last.tex",

                "mk/mk-xml.xml",

                "mk/mk-debug.png",
                "mk/mk-error.png",
                "mk/mk-last-state.pdf",

                "mk/mk-timing-1.tex",
                "mk/mk-timing-2.tex",
                "mk/mk-timing-3.tex",

                "mk/mk-timing-1-luatex-progress.lut",
                "mk/mk-timing-2-luatex-progress.lut",
                "mk/mk-timing-3-luatex-progress.lut",

                "mk/mk-luatex-progress.lut",
                "mk/luatexref-t-luatex-progress-intermediate.lut",
                "mk/luatexref-t-luatex-progress-runtime.lut",

            },
            results = {
                "mk/mk.pdf",
            },
        },
        ["hybrid"] = {
            status  = "okay",
            group   = "general/manuals/mkiv",
            runners = {
                "mtxrun --path=hybrid --script context hybrid",
            },
            sources = {
                "hybrid/hybrid.tex",
                "hybrid/hybrid-environment.tex",
                "hybrid/hybrid-titlepage.tex",
                "hybrid/hybrid-contents.tex",
                "hybrid/hybrid-introduction.tex",
                "hybrid/hybrid-languages.tex",
                "hybrid/hybrid-goodies.tex",
                "hybrid/hybrid-grouping.tex",
                "hybrid/hybrid-fontnames.tex",
                "hybrid/hybrid-bidi.tex",
                "hybrid/hybrid-inserts.tex",
                "hybrid/hybrid-mkvi.tex",
                "hybrid/hybrid-backend.tex",
                "hybrid/hybrid-callbacks.tex",
             -- "hybrid/hybrid-bibtex.tex",
                "hybrid/hybrid-parbuilder.tex",
                "hybrid/hybrid-tags.tex",
                "hybrid/hybrid-merge.tex",
                "hybrid/hybrid-export.tex",
                "hybrid/hybrid-optimize.tex",
                "hybrid/hybrid-characters.tex",
                "hybrid/hybrid-weird.tex",
                "hybrid/hybrid-glocal.tex",
                "hybrid/hybrid-math.tex",
                "hybrid/hybrid-mathml.tex",
                "hybrid/hybrid-ebooks.tex",
                "hybrid/hybrid-italics.tex",
                "hybrid/hybrid-partests.tex",
                "hybrid/hybrid-codebase.tex",
             -- "hybrid/hybrid-musings.tex",
                "hybrid/hybrid-jit.tex",
                "hybrid/hybrid-intermezzo.tex",

                "hybrid/benchmark-1.tex",
                "hybrid/benchmark-2.tex",
                "hybrid/benchmark-3.tex",
                "hybrid/benchmark-4.tex",
                "hybrid/benchmark-5.tex",

                "hybrid/exported-1.tex",
                "hybrid/exported-2.tex",
                "hybrid/exported-3.tex",
                "hybrid/exported-4.tex",
                "hybrid/exported-5.tex",
                "hybrid/exported-6.tex",
                "hybrid/exported-7.tex",
                "hybrid/exported-8.tex",
                "hybrid/exported-9.tex",
                "hybrid/exported-10.tex",
                "hybrid/exported-11.tex",
                "hybrid/exported-12.tex",
                "hybrid/exported-13.tex",

                "hybrid/tagged-001.png",
                "hybrid/tagged-002.png",
                "hybrid/tagged-003.png",
                "hybrid/tagged-004.png",
                "hybrid/tagged-005.png",
                "hybrid/tagged-006.png",
                "hybrid/tagged-007.png",
                "hybrid/tagged-008.png",
                "hybrid/tagged-009.png",
                "hybrid/tagged-010.png",
                "hybrid/tagged-011.png",

                "hybrid/calibri-fontshop.png",
                "hybrid/ebook-metafun-1.png",
                "hybrid/ebook-metafun-2.png",
                "hybrid/ebook-pdf.png",
                "hybrid/ebook-xhtml.png",
                "hybrid/mtx-server-ctx-fonttest.png",

                "hybrid/luatex-co-acceptablelowres.jpg",
            },
            results = {
                "hybrid/hybrid.pdf",
            },
        },
        ["about"] = {
            status  = "okay",
            group   = "general/manuals/mkiv",
            runners = {
                "mtxrun --path=about --script context about",
            },
            sources = {
                "about/about.tex",
                "about/about-environment.tex",
                "about/about-titlepage.tex",
                "about/about-contents.tex",
                "about/about-introduction.tex",
                "about/about-mathstackers.tex",
                "about/about-speed.tex",
                "about/about-mathstyles.tex",
                "about/about-calls.tex",
                "about/about-jitting.tex",
                "about/about-mobility.tex",
                "about/about-hz.tex",
                "about/about-nodes.tex",
                "about/about-expanding.tex",
                "about/about-nuts.tex",
                "about/about-hashing.tex",
                "about/about-properties.tex",
                "about/about-luafunctions.tex",
                "about/about-metafun.tex",
                "about/about-threequarters.tex",

                "about/pi-speed-1.tex",
                "about/pi-speed-2.tex",
                "about/pi-speed-3.tex",
                "about/pi-speed-4.tex",
                "about/pi-speed-5.tex",

                "/about/about-jitting-jit.lua",
                "/about/about-jitting-jit-2013-06-04.lua",
                "/about/demo-data.lua",
                "/about/luatest-hash-luajittex-073-JIT20.lua",
                "/about/luatest-hash-luajittex-073-LUA51.lua",
                "/about/luatest-hash-luajittex-073-LUA51-40-6.lua",
                "/about/luatest-hash-luatex-073-LUA52.lua",
                "/about/luatest-hash-luatex-073-LUA52-40-6.lua",

                "/about/still-expanding-1.png",
                "/about/still-expanding-2.png",
                "/about/still-expanding-3.png",
                "/about/still-expanding-4.png",
                "/about/still-expanding-5.png",
                "/about/still-expanding-6.png",
                "/about/still-expanding-7.png",
                "/about/still-expanding-8.png",
                "/about/still-expanding-9.png",
                "/about/still-expanding-10.png",
            },
            results = {
                "about/about.pdf",
            },
        },
        ["still"] = {
            status  = "okay",
            group   = "general/manuals/mkiv",
            runners = {
                "mtxrun --path=still --script context still",
            },
            sources = {
                "still/still.tex",
                "still/still-environment.tex",
                "still/still-titlepage.tex",
                "still/still-contents.tex",
                "still/still-introduction.tex",
                "still/still-math.tex",
                "still/still-simple.tex",
                "still/still-tokens.tex",
                "still/still-hack.tex",
                "still/still-profiling.tex",
                "still/still-opentypemath.tex",
                "still/still-expanding.tex",
                "still/still-backend.tex",
                "still/still-one.tex",

                "still/still-math-stripe.png",
                "still/still-acrobat-math.png",
                "still/still-acrobat-text.png",
                "still/still-sumatra-math.png",
                "still/still-sumatra-text.png",
            },
            results = {
                "still/still.pdf",
            },
        },
        ["magazines"] = {
            comment  = "These go into the their own path so we set the 'flat' flag.",
            status   = "okay",
            group    = "general/magazines",
            flat     = true,
            runners  = {
                "mtxrun --path=magazines --script context mag-0000-mkiv",
                "mtxrun --path=magazines --script context mag-0002-mkiv",
                "mtxrun --path=magazines --script context mag-0006-mkiv",
                "mtxrun --path=magazines --script context mag-0007-mkiv",
                "mtxrun --path=magazines --script context mag-0010-mkiv",
                "mtxrun --path=magazines --script context mag-1101-mkiv",
                "mtxrun --path=magazines --script context mag-1102-mkiv",
                "mtxrun --path=magazines --script context mag-1103-mkiv",
                "mtxrun --path=magazines --script context mag-1104-mkiv",
                "mtxrun --path=magazines --script context mag-1105-mkiv",
            },
            sources = {
                "magazines/mag-0000-mkiv.tex",
                "magazines/mag-0002-mkiv.tex",
                "magazines/mag-0006-mkiv.tex",
                "magazines/mag-0007-mkiv.tex",
                "magazines/mag-0010-mkiv.tex",
                "magazines/mag-1101-mkiv.tex",
                "magazines/mag-1102-mkiv.tex",
                "magazines/mag-1103-mkiv.tex",
                "magazines/mag-1104-mkiv.tex",
                "magazines/mag-1105-mkiv.tex",
            },
            results = {
                "magazines/mag-0000-mkiv.pdf",
                "magazines/mag-0002-mkiv.pdf",
                "magazines/mag-0006-mkiv.pdf",
                "magazines/mag-0007-mkiv.pdf",
                "magazines/mag-0010-mkiv.pdf",
                "magazines/mag-1101-mkiv.pdf",
                "magazines/mag-1102-mkiv.pdf",
                "magazines/mag-1103-mkiv.pdf",
                "magazines/mag-1104-mkiv.pdf",
                "magazines/mag-1105-mkiv.pdf",
            },
        },
        ["metafun"] = {
            status  = "okay",
            group   = "general/manuals/mkiv",
            runners = {
                "mtxrun --path=metafun --script context metafun --mode=paper  --result=metafun-p",
                "mtxrun --path=metafun --script context metafun --mode=screen --result=metafun-s",
            },
            sources = {
                "metafun/metafun.tex",

                "metafun/metafun-environment.tex",
                "metafun/metafun-environment-screen.tex",
                "metafun/metafun-environment-layout.tex",
                "metafun/metafun-environment-samples.tex",

                "metafun/metafun-titlepage-paper.tex",
                "metafun/metafun-titlepage-screen.tex",

                "metafun/metafun-introduction.tex",
                "metafun/metafun-contents.tex",
                "metafun/metafun-conventions.tex",

                "metafun/metafun-welcome.tex",
                "metafun/metafun-basics.tex",
                "metafun/metafun-embedding.tex",
                "metafun/metafun-layout.tex",
                "metafun/metafun-positioning.tex",
                "metafun/metafun-backgrounds.tex",
                "metafun/metafun-gadgets.tex",
                "metafun/metafun-effects.tex",
                "metafun/metafun-functions.tex",
                "metafun/metafun-text.tex",
                "metafun/metafun-debugging.tex",
                "metafun/metafun-styles.tex",
                "metafun/metafun-examples.tex",
                "metafun/metafun-macros.tex",
                "metafun/metafun-lua.tex",
                "metafun/metafun-graphics.tex",
                "metafun/metafun-sneaky.tex",

                "metafun/metafun-text-lmtx.tex",

             -- "metafun/metafun-programs.tex",
                "metafun/metafun-syntax.tex",
                "metafun/metafun-document.tex",
                "metafun/metafun-reference.tex",
             -- "metafun/metafun-literature.tex",

                "metafun/metafun-index.tex",

                "metafun/metafun-colofon.tex",
                "metafun/metafun-colofon-paper.tex",
                "metafun/metafun-colofon-screen.tex",

                "metafun/metafun-backpage.tex",

                "metafun/mycow.mp",
                "metafun/mycow.pdf",
                "metafun/somecow.pdf",
                "metafun/cow-fun.mps",
                "metafun/hacker.png",
                "metafun/gracht.mp",
                "metafun/m-1.png",
                "metafun/m-2.png",
                "metafun/mfun-mrun-demo.mp",

                "metafun/mfun-700.tex",
                "metafun/mfun-771.tex",
                "metafun/mfun-772.tex",
                "metafun/mfun-773.tex",
                "metafun/mfun-774.tex",
                "metafun/mfun-775.tex",
                "metafun/mfun-776.tex",
                "metafun/mfun-800.tex",
                "metafun/mfun-900.tex",
                "metafun/mfun-901.tex",
                "metafun/mfun-902.tex",
            },
            results = {
                "metafun/metafun-p.pdf",
                "metafun/metafun-s.pdf",
            },
        },
        ["onandon"] = {
            status  = "okay",
            group   = "general/manuals/mkiv",
            runners = {
                "mtxrun --path=onandon --script context onandon",
            },
            sources = {
                "onandon/onandon.tex",
                --
                "onandon/onandon-decade.tex",
                "onandon/onandon-ffi.tex",
                "onandon/onandon-variable.tex",
                "onandon/onandon-emoji.tex",
                "onandon/onandon-performance.tex",
                "onandon/onandon-editing.tex",
                "onandon/onandon-fences.tex",
                "onandon/onandon-media.tex",
                "onandon/onandon-53.tex",
                "onandon/onandon-execute.tex",
                "onandon/onandon-modern.tex",
                "onandon/onandon-expansion.tex",
                "onandon/onandon-runtoks.tex",
                "onandon/onandon-110.tex",
                --
                "onandon/onandon-speed-000.tex",
                "onandon/onandon-speed-001.tex",
                "onandon/onandon-speed-002.tex",
                "onandon/onandon-speed-003.tex",
                "onandon/onandon-speed-004.tex",
                "onandon/onandon-speed-005.tex",
                "onandon/onandon-speed-006.tex",
                "onandon/onandon-speed-007.tex",
                "onandon/onandon-speed-008.tex",
                "onandon/onandon-speed-009.tex",
                "onandon/onandon-speed-010.tex",
                "onandon/onandon-speed-011.tex",
                "onandon/onandon-speed-012.tex",
                --
             -- "onandon/tex-in-movie.jpg",
             -- "onandon/mathematics.png",
                "onandon/m-fonts-plugins-timings-luatex.lua",
                "onandon/m-fonts-plugins-timings-luajittex.lua",
             -- "onandon/tex-in-movie.jpg",
             -- "onandon/mathematics.png",
                "onandon/m-fonts-plugins-timings-luatex.lua",
                "onandon/m-fonts-plugins-timings-luajittex.lua",
                "onandon/onandon-seguiemj.tex",
                "onandon/onandon-seguiemj.pdf",
            },
            results = {
                "onandon/onandon.pdf",
            },
        },
        ["lowlevel"] = {
            status  = "okay",
            group   = "general/manuals/mkiv",
            runners = {
                "mtxrun --path=lowlevel --script context lowlevel",
                "mtxrun --path=lowlevel --script context lowlevel-conditionals",
                "mtxrun --path=lowlevel --script context lowlevel-boxes",
                "mtxrun --path=lowlevel --script context lowlevel-expansion",
                "mtxrun --path=lowlevel --script context lowlevel-registers",
                "mtxrun --path=lowlevel --script context lowlevel-macros",
                "mtxrun --path=lowlevel --script context lowlevel-grouping",
                "mtxrun --path=lowlevel --script context lowlevel-security",
                "mtxrun --path=lowlevel --script context lowlevel-characters",
                "mtxrun --path=lowlevel --script context lowlevel-scope",
                "mtxrun --path=lowlevel --script context lowlevel-paragraphs",
                "mtxrun --path=lowlevel --script context lowlevel-alignments",
                "mtxrun --path=lowlevel --script context lowlevel-marks",
                "mtxrun --path=lowlevel --script context lowlevel-inserts",
                "mtxrun --path=lowlevel --script context lowlevel-localboxes",
                "mtxrun --path=lowlevel --script context lowlevel-loops",
                "mtxrun --path=lowlevel --script context lowlevel-buffers",
                "mtxrun --path=lowlevel --script context lowlevel-tokens",
                "mtxrun --path=lowlevel --script context lowlevel-accuracy",
                "mtxrun --path=lowlevel --script context lowlevel-balancing",
                "mtxrun --path=lowlevel --script context lowlevel-lines",
                "mtxrun --path=lowlevel --script context lowlevel-debugging",
--                 "mtxrun --path=lowlevel --script context lowlevel-fonts",
                "mtxrun --path=lowlevel --script context lowlevel-pages",
                "mtxrun --path=lowlevel --script context lowlevel-expressions",
            },
            sources = {
                "lowlevel/lowlevel.tex",
                "lowlevel/lowlevel-style.tex",
                --
                "lowlevel/lowlevel-conditionals.tex",
                "lowlevel/lowlevel-boxes.tex",
                "lowlevel/lowlevel-expansion.tex",
                "lowlevel/lowlevel-registers.tex",
                "lowlevel/lowlevel-macros.tex",
                "lowlevel/lowlevel-grouping.tex",
                "lowlevel/lowlevel-security.tex",
                "lowlevel/lowlevel-characters.tex",
                "lowlevel/lowlevel-scope.tex",
                "lowlevel/lowlevel-paragraphs.tex",
                "lowlevel/lowlevel-alignments.tex",
                "lowlevel/lowlevel-marks.tex",
                "lowlevel/lowlevel-inserts.tex",
                "lowlevel/lowlevel-localboxes.tex",
                "lowlevel/lowlevel-loops.tex",
                "lowlevel/lowlevel-buffers.tex",
                "lowlevel/lowlevel-tokens.tex",
                "lowlevel/lowlevel-accuracy.tex",
                "lowlevel/lowlevel-balancing.tex",
                "lowlevel/lowlevel-lines.tex",
                "lowlevel/lowlevel-debugging.tex",
--                 "lowlevel/lowlevel-fonts.tex",
                "lowlevel/lowlevel-pages.tex",
                "lowlevel/lowlevel-expressions.tex",
            },
            results = {
                "lowlevel/lowlevel.pdf",
                "lowlevel/lowlevel-conditionals.pdf",
                "lowlevel/lowlevel-boxes.pdf",
                "lowlevel/lowlevel-expansion.pdf",
                "lowlevel/lowlevel-registers.pdf",
                "lowlevel/lowlevel-macros.pdf",
                "lowlevel/lowlevel-grouping.pdf",
                "lowlevel/lowlevel-security.pdf",
                "lowlevel/lowlevel-characters.pdf",
                "lowlevel/lowlevel-scope.pdf",
                "lowlevel/lowlevel-paragraphs.pdf",
                "lowlevel/lowlevel-alignments.pdf",
                "lowlevel/lowlevel-marks.pdf",
                "lowlevel/lowlevel-inserts.pdf",
                "lowlevel/lowlevel-localboxes.pdf",
                "lowlevel/lowlevel-loops.pdf",
                "lowlevel/lowlevel-buffers.pdf",
                "lowlevel/lowlevel-tokens.pdf",
                "lowlevel/lowlevel-accuracy.pdf",
                "lowlevel/lowlevel-balancing.pdf",
                "lowlevel/lowlevel-lines.pdf",
                "lowlevel/lowlevel-debugging.pdf",
--                 "lowlevel/lowlevel-fonts.pdf",
                "lowlevel/lowlevel-pages.pdf",
                "lowlevel/lowlevel-expressions.pdf",
            },
        },
        ["followingup"] = {
            status  = "okay",
            group   = "general/manuals/mkiv",
            runners = {
                "mtxrun --path=followingup --script context followingup",
            },
            sources = {
                "followingup/followingup.tex",
                "followingup/followingup-style.tex",
                "followingup/followingup-contents.tex",
                "followingup/followingup-titlepage.tex",

                "followingup/followingup-introduction.tex",
                "followingup/followingup-evolution.tex",
                "followingup/followingup-stripping.tex",
                "followingup/followingup-bitmaps.tex",
                "followingup/followingup-logging.tex",
                "followingup/followingup-directions.tex",
                "followingup/followingup-performance.tex",
                "followingup/followingup-cleanup.tex",
                "followingup/followingup-rejected.tex",
                "followingup/followingup-whatsits.tex",
                "followingup/followingup-feedback.tex",
                "followingup/followingup-lua.tex",
                "followingup/followingup-compilation.tex",
                "followingup/followingup-stubs.tex",
                "followingup/followingup-mp.tex",
                "followingup/followingup-tex.tex",
                "followingup/followingup-retrospect.tex",
                "followingup/followingup-fonts.tex",
                "followingup/followingup-memory.tex",
            },
            results = {
                "followingup/followingup.pdf",
            },
        },
        ["details"] = {
            status  = "okay",
            group   = "general/manuals/mkiv",
            runners = {
                "mtxrun --path=details --script context details --mode=print",
            },
            sources = {
                "details/details.tex",
                "details/details-environment.tex",
                --
                "details/details-frontpage.tex",
                "details/details-introduction.tex",
                "details/details-contents.tex",
                "details/details-index.tex",
                "details/details-colofon.tex",
                "details/details-backpage.tex",
                --
                "details/details-snappingheads.tex",
                "details/details-pseudocolumns.tex",
                "details/details-textbackgrounds.tex",
                "details/details-tuningformulas.tex",
                "details/details-floatingaround.tex",
                "details/details-finetuningfloats.tex",
                "details/details-ornaments.tex",
                "details/details-gridtrickery.tex",
                "details/details-captiontrickery.tex",
                --
                "details/back-0.tex",
                "details/back-1.tex",
                "details/back-2.tex",
                "details/back-3.tex",
                "details/back-4.tex",
                "details/back-5.tex",
                --
                "details/cow.pdf",
                "details/detcow.mp",
                "details/detcow.tex",
                "details/detcowmp.mps",
                "details/hacker.jpg",
                "details/mill.png",
            },
            results = {
                "details/details.pdf",
            },
        },
        ["examples"] = {
            status  = "okay",
            group   = "general/manuals/mkiv",
            runners = {
                "mtxrun --path=examples --script context examples-mathmeanings --mode=print",
            },
            sources = {
                "examples/examples-style.tex",
                "examples/examples-style-math.tex",
                --
                "examples/examples-mathmeanings.tex",
                "examples/examples-naturaltables.tex",
            },
            results = {
                "examples/examples-mathmeanings.pdf",
                "examples/examples-naturaltables.pdf",
            },
        },
        ["ppchtex"] = {
            status  = "okay",
            group   = "general/manuals/mkiv",
            runners = {
                "mtxrun --path=ppchtex --script context ppchtex-mkiv --mode=print",
            },
            sources = {
                "ppchtex/ppchtex-mkiv.tex",
                "ppchtex/ppchtex-mkiv-style.tex",
                --
                "ppchtex/ppchtex-mkiv-contents.tex",
                "ppchtex/ppchtex-mkiv-introduction.tex",
                "ppchtex/ppchtex-mkiv-structures.tex",
                "ppchtex/ppchtex-mkiv-bonds.tex",
                "ppchtex/ppchtex-mkiv-frontviews.tex",
                "ppchtex/ppchtex-mkiv-definitions.tex",
                "ppchtex/ppchtex-mkiv-combinations.tex",
                "ppchtex/ppchtex-mkiv-extratext.tex",
                "ppchtex/ppchtex-mkiv-axis.tex",
                "ppchtex/ppchtex-mkiv-setups.tex",
                "ppchtex/ppchtex-mkiv-symbols.tex",
                "ppchtex/ppchtex-mkiv-positioning.tex",
                "ppchtex/ppchtex-mkiv-reactions.tex",
                "ppchtex/ppchtex-mkiv-subscripts.tex",
                "ppchtex/ppchtex-mkiv-fonts.tex",
                "ppchtex/ppchtex-mkiv-color.tex",
                "ppchtex/ppchtex-mkiv-interaction.tex",
             -- "ppchtex/ppchtex-mkiv-extensions.tex",
             -- "ppchtex/ppchtex-mkiv-installation.tex",
             -- "ppchtex/ppchtex-mkiv-interfaces.tex",
                "ppchtex/ppchtex-mkiv-overview.tex",
            },
            results = {
                "ppchtex/ppchtex-mkiv.pdf",
            },
        },
    },
}
