return {
    category  = "documentation",
    targets   = {
        tree  = {
            sources = "doc/context/sources/documents",
            results = "doc/context/documents",
            objects = { "sources", "results" }
        },
        site = {
            sources = "sources/documents", -- placeholder
            results = "documents",
            objects = { "results" }
        },
    },
    documents = {
        ["excursion"] = {
            status  = "okay",
            group   = "general/manuals/mkxl",
            runners = {
                "mtxrun --path=excursion/en --script context excursion-en",
             -- "mtxrun --path=excursion/en --script context excursion-en --mode=Screen",
             -- "mtxrun --path=excursion/en --script context excursion-en --mode=Book",
            },
            sources = {
                "excursion/excursion.mkxl",
                "excursion/excursion-abbreviations.mkxl",
                "excursion/excursion-colofon.mkxl",
                "excursion/excursion-copyright.mkxl",
                "excursion/excursion-graphics.mkxl",
                "excursion/excursion-hyphenations.mkxl",
                "excursion/excursion-links.mkxl",
                "excursion/excursion-screen.mkxl",
                "excursion/excursion-style.mkxl",

                "excursion/en/excursion-en-hasselt.bib",

                "excursion/en/excursion-en.mkxl",
                "excursion/en/excursion-en-alignments.mkxl",
                "excursion/en/excursion-en-arranging.mkxl",
                "excursion/en/excursion-en-backpagetext.mkxl",
                "excursion/en/excursion-en-bibliography.mkxl",
                "excursion/en/excursion-en-charts.mkxl",
                "excursion/en/excursion-en-chemical.mkxl",
                "excursion/en/excursion-en-columns.mkxl",
                "excursion/en/excursion-en-commandindex.mkxl",
                "excursion/en/excursion-en-commandlist.mkxl",
                "excursion/en/excursion-en-commands.mkxl",
                "excursion/en/excursion-en-composedcharacters.mkxl",
                "excursion/en/excursion-en-context-web.mkxl",
                "excursion/en/excursion-en-create-textbook.mkxl",
                "excursion/en/excursion-en-descriptions.mkxl",
                "excursion/en/excursion-en-enumerations.mkxl",
                "excursion/en/excursion-en-errors.mkxl",
                "excursion/en/excursion-en-figures.mkxl",
                "excursion/en/excursion-en-fonts.mkxl",
                "excursion/en/excursion-en-footnotes.mkxl",
                "excursion/en/excursion-en-framed-paragraphs.mkxl",
                "excursion/en/excursion-en-framedtexts.mkxl",
                "excursion/en/excursion-en-frames.mkxl",
                "excursion/en/excursion-en-gettingstarted.mkxl",
                "excursion/en/excursion-en-hasseltbook.mkxl",
                "excursion/en/excursion-en-headers.mkxl",
                "excursion/en/excursion-en-headings.mkxl",
                "excursion/en/excursion-en-interactivity.mkxl",
                "excursion/en/excursion-en-introduction.mkxl",
                "excursion/en/excursion-en-itemizations.mkxl",
                "excursion/en/excursion-en-language.mkxl",
                "excursion/en/excursion-en-layers.mkxl",
                "excursion/en/excursion-en-layout.mkxl",
                "excursion/en/excursion-en-listofmanuals.mkxl",
                "excursion/en/excursion-en-margintexts.mkxl",
                "excursion/en/excursion-en-math.mkxl",
                "excursion/en/excursion-en-mathcharacters.mkxl",
                "excursion/en/excursion-en-metapost.mkxl",
                "excursion/en/excursion-en-modes.mkxl",
                "excursion/en/excursion-en-modules.mkxl",
                "excursion/en/excursion-en-overlays.mkxl",
                "excursion/en/excursion-en-pagebackgrounds.mkxl",
                "excursion/en/excursion-en-pages.mkxl",
                "excursion/en/excursion-en-paragraphs.mkxl",
                "excursion/en/excursion-en-pdfa.mkxl",
                "excursion/en/excursion-en-presentations.mkxl",
                "excursion/en/excursion-en-processingfiles.mkxl",
                "excursion/en/excursion-en-quotation.mkxl",
                "excursion/en/excursion-en-references.mkxl",
                "excursion/en/excursion-en-registers.mkxl",
                "excursion/en/excursion-en-runtimefiles.mkxl",
                "excursion/en/excursion-en-screen-extract-page.mkxl",
                "excursion/en/excursion-en-setupcommands.mkxl",
                "excursion/en/excursion-en-sortedlists.mkxl",
                "excursion/en/excursion-en-specialcharacters.mkxl",
                "excursion/en/excursion-en-structure.mkxl",
                "excursion/en/excursion-en-subjectindex.mkxl",
                "excursion/en/excursion-en-synonyms.mkxl",
                "excursion/en/excursion-en-system-install.mkxl",
                "excursion/en/excursion-en-tables.mkxl",
                "excursion/en/excursion-en-tablesofcontent.mkxl",
                "excursion/en/excursion-en-tabulations.mkxl",
                "excursion/en/excursion-en-test.mkxl",
                "excursion/en/excursion-en-textbackgrounds.mkxl",
                "excursion/en/excursion-en-texteditor.mkxl",
                "excursion/en/excursion-en-trackers.mkxl",
                "excursion/en/excursion-en-units.mkxl",
                "excursion/en/excursion-en-usersetups.mkxl",
                "excursion/en/excursion-en-whatever.mkxl",

                "excursion/graphics/excursion-en-buttons.mkxl",
                "excursion/graphics/firstdocument.mkxl",
                "excursion/graphics/minibook-en.mkxl",
                "excursion/graphics/cow.pdf",
                "excursion/graphics/excursion-00.pdf",
                "excursion/graphics/excursion-cover-background.pdf",
                "excursion/graphics/excursion-en-buttons.pdf",
                "excursion/graphics/excursion-en-fig-screenshot.pdf",
                "excursion/graphics/firstdocument.pdf",
                "excursion/graphics/minibook-en.pdf",
                "excursion/graphics/excursion-01.png",
                "excursion/graphics/excursion-03.png",
                "excursion/graphics/excursion-04.png",
                "excursion/graphics/excursion-07.png",
                "excursion/graphics/excursion-08.png",
                "excursion/graphics/excursion-12.png",
                "excursion/graphics/excursion-13.png",
                "excursion/graphics/excursion-15.png",
                "excursion/graphics/excursion-16.png",
                "excursion/graphics/excursion-18.png",
                "excursion/graphics/excursion-19.png",
                "excursion/graphics/excursion-20.png",
                "excursion/graphics/excursion-21.png",
                "excursion/graphics/excursion-22.png",
                "excursion/graphics/excursion-23.png",
                "excursion/graphics/excursion-24.png",
                "excursion/graphics/excursion-25.png",
                "excursion/graphics/excursion-26.png",
                "excursion/graphics/excursion-27.png",
                "excursion/graphics/excursion-28.png",
                "excursion/graphics/excursion-29.png",
                "excursion/graphics/excursion-en-fig-page-areas.png",
                "excursion/graphics/excursion-en-fig-page-parameters.png",
            },
            results = {
                "excursion/en/excursion-en.pdf",
            },
        },
        ["mathincontext"] = {
            status  = "okay", -- work in progress
            group   = "general/manuals/mkxl",
            runners = {
             -- "mtxrun --path=mathincontext --script context mathincontext-pagegraphics",
                "mtxrun --path=mathincontext --script context mathincontext --mode=screen --result=mathincontext-screen",
                "mtxrun --path=mathincontext --script context mathincontext --mode=paper  --result=mathincontext-paper",
             -- "mtxrun --path=mathincontext --script context mathincontext --mode=access --result=mathincontext-access",
            },
            sources = {
                -- todo
            },
            results = {
                "mathincontext/mathincontext-screen.pdf",
                "mathincontext/mathincontext-paper.pdf",
             -- "mathincontext/mathincontext-access.pdf",
            },
        },
        ["tagging"] = {
            status  = "okay",
            group   = "general/manuals/mkxl",
            runners = {
                "mtxrun --path=tagging --script context tagging",
                "mtxrun --path=tagging --script context standards",
             -- "mtxrun --path=tagging --script context pdftags",
            },
            sources = {
                "tagging/tagging.tex",
                "tagging/standards.tex",
             -- "tagging/pdftags.tex", -- MAPS 2025
            },
            results = {
                "tagging/tagging.pdf",
                "tagging/standards.pdf",
             -- "tagging/pdftags.pdf",
            },
        },
        ["signals"] = {
            status  = "okay",
            group   = "general/manuals/mkxl",
            runners = {
                "mtxrun --path=signals --script context signals",
            },
            sources = {
                "signals/signals.tex",
                "signals/signals-macos.tex",
            },
            results = {
                "signals/signals.pdf",
                "signals/signals-macos.pdf",
            },
        },
        ["little-context-book"] = {
            status  = "okay",
            group   = "general/manuals/mkxl",
            runners = {
                "mtxrun --path=signals --script context little-context-book",
            },
            sources = {
                "signals/little-context-book.tex",
                "signals/little-context-book-002.jpg",
            },
            results = {
                "signals/little-context-book.pdf",
            },
        },
        ["luametatex"] = {
            status  = "okay",
            group   = "general/manuals/mkxl",
            runners = {
                "mtxrun --path=luametatex --script context luametatex",
             -- "mtxrun --path=luametatex --script context luametatex-primitives",
            },
            sources = {
                "luametatex/luametatex.tex",

                "luametatex/luametatex-style.tex",

                "luametatex/luametatex-contents.tex",
                "luametatex/luametatex-introduction.tex",

                "luametatex/luametatex-engines.tex",
                "luametatex/luametatex-principles.tex",
                "luametatex/luametatex-constructions.tex",
                "luametatex/luametatex-assumptions.tex",
                "luametatex/luametatex-internals.tex",
                "luametatex/luametatex-primitives.tex",
                "luametatex/luametatex-callbacks.tex",
                "luametatex/luametatex-fonts.tex",
                "luametatex/luametatex-languages.tex",
                "luametatex/luametatex-lua.tex",
                "luametatex/luametatex-metapost.tex",
                "luametatex/luametatex-tex.tex",
                "luametatex/luametatex-math.tex",
                "luametatex/luametatex-pdf.tex",
                "luametatex/luametatex-nodes.tex",
                "luametatex/luametatex-tokens.tex",
                "luametatex/luametatex-libraries.tex",
                "luametatex/luametatex-security.tex",
            },
            results = {
                "luametatex/luametatex.pdf",
            },
        },
        ["luametafun"] = {
            status  = "okay",
            group   = "general/manuals/mkxl",
            runners = {
                "mtxrun --path=luametafun --script context luametafun",
                "mtxrun --path=luametafun --script context threed",
            },
            sources = {
                "luametafun/luametafun.tex",
                "luametafun/luametafun-style.tex",
                "luametafun/luametafun-titlepage.tex",
                "luametafun/luametafun-contents.tex",
                "luametafun/luametafun-introduction.tex",
                "luametatex/luametafun-extensions.tex",
                "luametafun/luametafun-technology.tex",
                "luametafun/luametafun-text.tex",
                "luametafun/luametafun-function.tex",
                "luametafun/luametafun-contour.tex",
                "luametafun/luametafun-surface.tex",
                "luametafun/luametafun-grid.tex",
                "luametafun/luametafun-axis.tex",
                "luametafun/luametafun-outline.tex",
                "luametafun/luametafun-followtext.tex",
                "luametafun/luametafun-placeholder.tex",
                "luametafun/luametafun-arrow.tex",
                "luametafun/luametafun-chart.tex",
                "luametafun/luametafun-mesh.tex",
                "luametafun/luametafun-groups.tex",
                "luametafun/luametafun-shade.tex",
                "luametafun/luametafun-svg.tex",
                "luametafun/luametafun-poisson.tex",
                "luametafun/luametafun-fonts.tex",
                "luametafun/luametafun-color.tex",
                "luametafun/luametafun-lines.tex",
                "luametafun/luametafun-interface.tex",
                "luametafun/luametafun-paths.tex",
                "luametafun/luametafun-envelope.tex",
                "luametafun/luametafun-potrace.tex",
                "luametafun/luametafun-bytemaps.tex",
                "luametafun/luametafun-noise.tex",
                "luametafun/luametafun-synchronizers.tex",
                "luametafun/luametafun-performance.tex",
                "luametafun/luametafun-whatever.tex",
                "luametafun/luametafun-oscillate.tex",
                "luametafun/luametafun-threed.tex",
                "luametafun/luametafun-voronoi.tex",
                "luametafun/luametafun-syntax.tex",
                "luametafun/luametafun-extensions.tex",
                --
                "luametafun/mozilla-svg-001.svg",
                "luametafun/mozilla-svg-002.svg",
                "luametafun/luametafun-mesh-examples.tex",
                "luametafun/luametafun-threed-sphere.stl",
                "luametafun/luametafun-voronoi-001.tex",
                "luametafun/luametafun-voronoi-001.png",

                "luametafun/threed.tex",
            },
            results = {
                "luametafun/luametafun.pdf",
                "luametafun/threed.pdf",
            },
        },
        ["beyond"] = {
            status  = "okay",
            group   = "general/manuals/mkxl",
            runners = {
                "mtxrun --path=beyond --script context beyond",
            },
            sources = {
                "beyond/beyond.tex",
                "beyond/beyond-style.tex",
                "beyond/beyond-contents.tex",
                "beyond/beyond-titlepage.tex",
                --
                "beyond/beyond-introduction.tex",
                "beyond/beyond-twins.tex",
                "beyond/beyond-paragraphs.tex",
                "beyond/beyond-namespaces.tex",
                "beyond/beyond-bonus.tex",
                "beyond/beyond-whatif.tex",
                "beyond/beyond-expression.tex",

             -- "beyond/beyond-tagging.tex",
             -- "beyond/beyond-noisy.tex",
             -- "beyond/beyond-metapost.tex",
             -- "beyond/beyond-pages.tex",
             -- "beyond/beyond-balancing.tex",
             -- "beyond/beyond-protection.tex",
             -- "beyond/beyond-howcomplex.tex", -- article
             -- "beyond/beyond-programming.tex",
             -- "beyond/beyond-looseness.tex",  -- article
             -- "beyond/beyond-lsystems.tex",   -- article

                "beyond/beyond-alignments.tex",
                "beyond/beyond-hanging.tex",
                "beyond/beyond-snapping.tex",
                "beyond/beyond-inserts.tex",

                "beyond/a-p-101.png",
                "beyond/a-p-258.png",
                "beyond/a-p-27.png",
                "beyond/a-p-29.png",
                "beyond/a-p-3.png",
                "beyond/a-p-43.png",
                "beyond/a-p-55.png",
                "beyond/a-p-60.png",
                "beyond/a-p-76.png",
                "beyond/a-t-101.png",
                "beyond/a-t-258.png",
                "beyond/a-t-27.png",
                "beyond/a-t-29.png",
                "beyond/a-t-3.png",
                "beyond/a-t-43.png",
                "beyond/a-t-55.png",
                "beyond/a-t-60.png",
                "beyond/a-t-76.png",

                "beyond/beyond-twins-001.png",
                "beyond/beyond-twins-002.png",
                "beyond/beyond-twins-003.png",
                "beyond/beyond-twins-011.png",
                "beyond/beyond-twins-012.png",
                "beyond/beyond-twins-013.png",
                "beyond/beyond-twins-014.png",
                "beyond/beyond-twins-015.png",
                "beyond/beyond-twins-016.png",
                "beyond/beyond-twins-017.png",
                "beyond/beyond-twins-018.png",
                "beyond/beyond-twins-021.png",

             -- "beyond/columns-hhmps.pdf",

             -- "beyond/beyond-tagging-qr.png",
             -- "beyond/beyond-tagging-eartags.jpg",
             -- "beyond/beyond-tagging-flags-1.jpg",
             -- "beyond/beyond-tagging-flags-2.jpg",
             -- "beyond/beyond-tagging-goats.jpg",
             -- "beyond/beyond-tagging-prototype.jpg",
             -- "beyond/beyond-tagging-qrtags.jpg",
             -- "beyond/beyond-tagging-w.jpg",

             -- "beyond/mesh-mikaelfun-1-1.lua",

             -- "beyond/beyond-metapost-dot.tex",
             -- "beyond/beyond-metapost-quad.tex",
             -- "beyond/beyond-metapost-line.tex",

            },
            results = {
                "beyond/beyond.pdf",
            },
        },
        ["moretocome"] = {
            status  = "okay",
            group   = "general/manuals/mkxl",
            runners = {
                "mtxrun --path=moretocome --script context moretocome",
            },
            sources = {
                "moretocome/moretocome.tex",
                "moretocome/moretocome-style.tex",
                "moretocome/moretocome-contents.tex",
                "moretocome/moretocome-titlepage.tex",
                --
                "moretocome/moretocome-introduction.tex",
                "moretocome/moretocome-bordercases.tex",
                "moretocome/moretocome-optimizations.tex",
                "moretocome/moretocome-integration.tex",   -- first in the maps
            },
            results = {
                "moretocome/moretocome.pdf",
            },
        },
        ["canbedone"] = {
            status  = "okay",
            group   = "general/manuals/mkxl",
            runners = {
                "mtxrun --path=canbedone --script context canbedone",
                "mtxrun --path=canbedone --script context canbedone-periods",
            },
            sources = {
                "canbedone/canbedone.tex",
                "canbedone/canbedone-style.tex",
                "canbedone/canbedone-periods.tex",
                "canbedone/canbedone-clipping.tex",
                "canbedone/canbedone-balancing.tex",
            },
            results = {
                "canbedone/canbedone.pdf",
                "canbedone/canbedone-periods.pdf",
            },
        },
        ["drawinglines"] = {
            status  = "okay",
            group   = "general/manuals/mkxl",
            runners = {
                "mtxrun --path=drawinglines --script context drawinglines --mode=print",
            },
            sources = {
                "drawinglines/drawinglines.tex",
                "drawinglines/drawinglines-taggedpdf.tex",
                "drawinglines/drawinglines-mathml.tex",
             -- "drawinglines/drawinglines-performance.tex",
                "drawinglines/drawinglines-instances.tex",

                "2024-07-01-001-amaya.png",
                "2024-07-01-001-chrome.png",
                "2024-07-01-001-firefox.png",
                "2024-07-02-001-chrome.png",
                "2024-07-02-001-firefox.png",
                "2024-07-02-002-chrome.png",
                "2024-07-02-002-firefox.png",
                "2024-07-02-003-firefox-10pt-100pct.png",
                "2024-07-02-003-firefox-10pt-200pct.png",
                "2024-07-02-003-firefox-20pt-200pct.png",
                "2024-07-15-001-firefox.png",
            },
            results = {
                "drawinglines/drawinglines.pdf",
            },
        },
        ["ontarget"] = {
            status  = "okay",
            group   = "general/manuals/mkxl",
            runners = {
                "mtxrun --path=ontarget --script context ontarget",
            },
            sources = {
                "ontarget/ontarget.tex",
                "ontarget/ontarget-style.tex",
                "ontarget/ontarget-contents.tex",
                "ontarget/ontarget-titlepage.tex",
                --
                "ontarget/ontarget-introduction.tex",
                "ontarget/ontarget-eventually.tex",
                "ontarget/ontarget-dk.tex",
                "ontarget/ontarget-anchoring.tex",
                "ontarget/ontarget-math.tex",
                "ontarget/ontarget-binary.tex",
                "ontarget/ontarget-metapost.tex",
                "ontarget/ontarget-makesnosense.tex",
                "ontarget/ontarget-makessense.tex",
                "ontarget/ontarget-alsomath.tex",
                "ontarget/ontarget-ridofjit.tex",
                "ontarget/ontarget-gettingridof.tex",
                "ontarget/ontarget-registers.tex",
                "ontarget/ontarget-fairphone.tex",
                "ontarget/ontarget-green.tex",
                "ontarget/ontarget-jmn.tex",
                "ontarget/ontarget-profiles.tex",
                "ontarget/ontarget-envelopes.tex",
                "ontarget/ontarget-mathfonts.tex",
                "ontarget/ontarget-mathsizes.tex",
                "ontarget/ontarget-constants.tex",
                "ontarget/ontarget-active.tex",
                "ontarget/ontarget-accuracy.tex",
                "ontarget/ontarget-mathcharacters",
                "ontarget/ontarget-standardize.tex",
                "ontarget/ontarget-radicals.tex",
                "ontarget/ontarget-bars.tex",
                "ontarget/ontarget-rules.tex",
                "ontarget/ontarget-bitmaps.tex",
                "ontarget/ontarget-rivers.tex",
                "ontarget/ontarget-inclusion.tex",
                "ontarget/ontarget-signing.tex",
                "ontarget/ontarget-authentic.tex",
                "ontarget/ontarget-pagestreams.tex",
                "ontarget/ontarget-mathml.tex",
                "ontarget/ontarget-nostalgic.tex",
                "ontarget/ontarget-pdf-2.tex",

                "ontarget/ontarget-nostalgic-pgc.pdf",
                "ontarget/ontarget-nostalgic.zip",

                "ontarget/ontarget-mathml-example.tex",
                "ontarget/ontarget-mathml-meanings.pdf",

                "ontarget/ontarget-rules-001.jpg",

                "ontarget/ontarget-authentic-001.png",
                "ontarget/ontarget-authentic-002.png",
                "ontarget/ontarget-authentic-003.png",
                "ontarget/ontarget-authentic-004.png",

                "ontarget/ontarget-cmr10.600pk",    --maybe zip
                "ontarget/ontarget-cmr10.2400pk",
                "ontarget/ontarget-cmr10.7200pk",
                "ontarget/ontarget-cmr10.pk",
                "ontarget/ontarget-cmr10.tfm",
                "ontarget/ontarget-cmr.enc",

                "ontarget/ontarget-bitmaps-device",

                "ontarget/ontarget-standardize-001.png",
                "ontarget/ontarget-standardize-002.png",
                "ontarget/ontarget-standardize-003.pdf",
                "ontarget/ontarget-standardize-004.png",
                "ontarget/ontarget-standardize-005.png",
                "ontarget/ontarget-standardize-006.png",
                "ontarget/ontarget-standardize-007.png",
                "ontarget/ontarget-standardize-008.png",
                "ontarget/ontarget-standardize-009.png",
                "ontarget/ontarget-standardize-010.png",
                "ontarget/ontarget-standardize-011.png",
                "ontarget/ontarget-standardize-012.png",
                "ontarget/ontarget-standardize-013.png",
                "ontarget/ontarget-standardize-014.pdf",
                "ontarget/ontarget-standardize-015.pdf",
                "ontarget/ontarget-standardize-016.pdf",
            },
            results = {
                "ontarget/ontarget.pdf",
            },
        },
        ["evenmore"] = {
            status  = "okay",
            group   = "general/manuals/mkxl",
            runners = {
                "mtxrun --path=evenmore --script context evenmore",
            },
            sources = {
                "evenmore/evenmore.tex",
                "evenmore/evenmore-style.tex",
                "evenmore/evenmore-contents.tex",
                "evenmore/evenmore-titlepage.tex",
                --
                "evenmore/evenmore-introduction.tex",
                "evenmore/evenmore-pi.tex",
                "evenmore/evenmore-fonts.tex",
                "evenmore/evenmore-threesix.tex",
                "evenmore/evenmore-normalization.tex",
                "evenmore/evenmore-expansion.tex",
                "evenmore/evenmore-libraries.tex",
                "evenmore/evenmore-whattex.tex",
                "evenmore/evenmore-numbers.tex",
                "evenmore/evenmore-parameters.tex",
                "evenmore/evenmore-parsing.tex",
                "evenmore/evenmore-tokens.tex",
                "evenmore/evenmore-keywords.tex",
                "evenmore/evenmore-paragraphs.tex",
                "evenmore/evenmore-hyphenation.tex",
                "evenmore/evenmore-bitwise.tex",
                "evenmore/evenmore-offloading.tex",
                "evenmore/evenmore-inserts.tex",
                "evenmore/evenmore-formats.tex",
                "evenmore/evenmore-expressions.tex",
                --
                "evenmore/mozilla-svg-001.svg",
            },
            results = {
                "evenmore/evenmore.pdf",
            },
        },
        ["svg"] = {
            status  = "okay",
            group   = "general/manuals/mkxl",
            runners = {
                "mtxrun --path=svg --script context svg-lmtx",
            },
            sources = {
                "svg/svg-lmtx.tex",
                "svg/svg-lmtx-microsoft.lua",
                "svg/svg-lmtx-mozilla.lua",
                "svg/mozilla-tiger.svg",
                "svg/svglogo.svg",
            },
            results = {
                "svg/svg-lmtx.pdf",
            },
        },
        ["mvlcolumnsets"] = {
            status  = "okay",
            group   = "general/manuals/mkxl",
            runners = {
                "mtxrun --path=mvlcolumnsets --script context mvlcolumnsets --mode=final",
            },
            sources = {
                "mvlcolumnsets/mvlcolumnsets.tex",
                "mvlcolumnsets/mvlcolumnsets-000.tex",
                --
                "mvlcolumnsets/mvlcolumnsets-001.tex",
                "mvlcolumnsets/mvlcolumnsets-002.tex",
                "mvlcolumnsets/mvlcolumnsets-003.tex",
                "mvlcolumnsets/mvlcolumnsets-004.tex",
                "mvlcolumnsets/mvlcolumnsets-005.tex",
                "mvlcolumnsets/mvlcolumnsets-006.tex",
                "mvlcolumnsets/mvlcolumnsets-007.tex",
                "mvlcolumnsets/mvlcolumnsets-008.tex",
                --
                "mvlcolumnsets/mvlcolumnsets-101.tex",
                "mvlcolumnsets/mvlcolumnsets-102.tex",
                "mvlcolumnsets/mvlcolumnsets-103.tex",
                --
                "mvlcolumnsets/mvlcolumnsets-201.tex",
                "mvlcolumnsets/mvlcolumnsets-202.tex",
                "mvlcolumnsets/mvlcolumnsets-203.tex",
                "mvlcolumnsets/mvlcolumnsets-204.tex",
                "mvlcolumnsets/mvlcolumnsets-206.tex",
                --
             -- "mvlcolumnsets/mvlcolumnsets-301.tex",
                --
                "mvlcolumnsets/mvlcolumnsets-401.tex",
                "mvlcolumnsets/mvlcolumnsets-402.tex",
                "mvlcolumnsets/mvlcolumnsets-403.tex",
                "mvlcolumnsets/mvlcolumnsets-404.tex",
                "mvlcolumnsets/mvlcolumnsets-405.tex",
                --
                "mvlcolumnsets/mvlcolumnsets-601.tex",
                --
                "mvlcolumnsets/mvlcolumnsets-701.tex",
                "mvlcolumnsets/mvlcolumnsets-702.tex",
                "mvlcolumnsets/mvlcolumnsets-703.tex",
                "mvlcolumnsets/mvlcolumnsets-704.tex",
                --
             -- "mvlcolumnsets/mvlcolumnsets-801.tex",
             -- "mvlcolumnsets/mvlcolumnsets-802.tex",
             -- "mvlcolumnsets/mvlcolumnsets-803.tex",
             -- "mvlcolumnsets/mvlcolumnsets-804.tex",
             -- "mvlcolumnsets/mvlcolumnsets-805.tex",
             -- "mvlcolumnsets/mvlcolumnsets-806.tex",
                --
                "mvlcolumnsets/mvlcolumnsets-901.tex",
                "mvlcolumnsets/mvlcolumnsets-902.tex",
             -- "mvlcolumnsets/mvlcolumnsets-903.tex",
                --
                "mvlcolumnsets/mvlcolumnsets-1010.tex",
                "mvlcolumnsets/mvlcolumnsets-1011.tex",
            },
        },
        ["fontspecial"] = {
            status  = "okay",
            group   = "general/manuals/mkxl",
            runners = {
                "mtxrun --path=fontspecial --script context font-special --mode=final",
            },
            sources = {
                "fontspecial/font-special.mkxl",
                "fontspecial/pc-i-061.xml",
                "fontspecial/wh-s-002.xml",
                "fontspecial/wh-g-016.xml",
                "fontspecial/wh-o-002.xml",
                "fontspecial/wh-o-003.xml",
                "fontspecial/pc-d-007.xml",
            },
        },
        ["scite"] = {
            status  = "okay",
            group   = "general/manuals/mkxl",
            runners = {
                "mtxrun --path=excursion/en --script context scite-context-readme",
            },
            sources = {
                "scite/scite-context-readme.tex",
            },
            results = {
                "scite/scite-context-readme.pdf",
            },
        },
        ["ecmascript"] = {
            status  = "okay",
            group   = "general/manuals/mkxl",
            runners = {
                "mtxrun --path=ecmascript --script context ecmascript-mkxl",
            },
            sources = {
                "ecmascript/ecmascript-mkxl.tex",
            },
            results = {
                "ecmascript/ecmascript-mkxl.pdf",
            },
        },
        ["mwe"] = {
            status  = "okay",
            group   = "general/manuals/mkxl",
            runners = {
                "mtxrun --path=mwe --script context mwe",
            },
            sources = {
                "mwe/mwe.tex",
            },
            results = {
                "mwe/mwe.pdf",
            },
        },
        ["leaflets"] = {
            comment  = "These go into the their own path so we set the 'flat' flag.",
            status  = "okay",
            group   = "general/leaflets/mkxl",
            flat    = true,
            runners = {
                "mtxrun --path=leaflets --script context leaflet-context",
                "mtxrun --path=leaflets --script context leaflet-luametatex",
                "mtxrun --path=leaflets --script context leaflet-mixing",
            },
            sources = {
                "leaflets/leaflet-common.tex",
                "leaflets/leaflet-context.tex",
                "leaflets/leaflet-luametatex.tex",
                "leaflets/leaflet-mixing.tex",
            },
            results = {
                "leaflets/leaflet-context.pdf",
                "leaflets/leaflet-luametatex.pdf",
                "leaflets/leaflet-mixing.pdf",
            },
        },
    },
}
